# Generated by Django 2.0.7 on 2018-07-29 19:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalibrationBundle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('rois_conf', models.TextField()),
                ('tracking_conf', models.TextField()),
                ('events_conf', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='CalibrationVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.CharField(max_length=1000)),
                ('recording_date', models.DateTimeField(verbose_name='date recorded')),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=200)),
                ('event_params', models.TextField()),
                ('creation_date', models.DateTimeField(verbose_name='date created')),
                ('calibration_bundle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.CalibrationBundle')),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('calibration_bundle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shancms.CalibrationBundle')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.Company')),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField(max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='shelf',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.Venue'),
        ),
        migrations.AddField(
            model_name='event',
            name='shelf',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.Shelf'),
        ),
        migrations.AddField(
            model_name='calibrationvideo',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.Company'),
        ),
        migrations.AddField(
            model_name='calibrationbundle',
            name='calibration_video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shancms.CalibrationVideo'),
        ),
    ]
